### ISSUE TITLE
Tuple.map calls obfuscate errors

### ISSUE THREAD

**Issue by jakebeal** [Protelis/Protelis#158] opened 2018-10-15 18:16 UTC
When calling Tuple.map on a Protelis function, if there is an error in the function called, the call bombs out with an error saying that Map cannot be invoked, rather than actually showing the error from the function.

**Comment by jakebeal** [comment] 2019-03-12 20:51
This is a specific case of a more general issue in ReflectionUtils.invokeMethod, which should distinguish its reporting between "cannot invoke method" and "invoked method failed"

**Comment by DanySK** [comment] 2019-03-26 13:20
Hi @jakebeal,
do you have an example of a bad stacktrace and a description of the information you'd like to see instead?

**Comment by jakebeal** [comment] 2019-03-26 16:38
Here is an example (slightly edited for release reasons).
Notice that is says: "cannot invoke ... on null", which led us down several wrong paths.
The problem is actually the `ConcurrentModificationException` being raised inside the method, which has nothing to do with Protelis.

The error message should:
1. Just it's a static method, rather than "invoke ... on null"
2. Say that the problem is an exception inside the function, not that it cannot invoke the function, which sounds like the call never gets started.

```
16:10:32 ERROR Main:162 - Unexpected exception in Protelis
java.lang.IllegalStateException: Cannot invoke public static java.util.Set com.bbn.SOME_METHOD(java.util.Set,java.util.Set) with arguments [REASONABLE_ARGUMENTS] on null
    at org.protelis.lang.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:235)
    at org.protelis.lang.util.ReflectionUtils.invokeFieldable(ReflectionUtils.java:198)
    at org.protelis.lang.interpreter.impl.MethodCall.eval(MethodCall.java:108)
    at org.protelis.lang.interpreter.impl.All.eval(All.java:59)
    at org.protelis.lang.interpreter.impl.FunctionCall.eval(FunctionCall.java:87)
    at org.protelis.lang.interpreter.impl.DotOperator.eval(DotOperator.java:102)
    at org.protelis.lang.interpreter.impl.All.eval(All.java:59)
    at org.protelis.lang.interpreter.impl.AbstractAnnotatedTree.evalInNewStackFrame(AbstractAnnotatedTree.java:296)
    at org.protelis.lang.interpreter.impl.RepCall.eval(RepCall.java:71)
    at org.protelis.lang.interpreter.impl.All.eval(All.java:59)
    at org.protelis.lang.interpreter.impl.FunctionCall.eval(FunctionCall.java:87)
    at org.protelis.lang.interpreter.impl.All.eval(All.java:59)
    at org.protelis.lang.interpreter.impl.FunctionCall.eval(FunctionCall.java:87)
    at org.protelis.lang.interpreter.impl.AbstractAnnotatedTree.lambda$projectAndEval$1(AbstractAnnotatedTree.java:230)
    at org.protelis.lang.interpreter.impl.AbstractAnnotatedTree.access$lambda$1(AbstractAnnotatedTree.java)
    at org.protelis.lang.interpreter.impl.AbstractAnnotatedTree$$Lambda$2.accept(Unknown Source)
    at org.protelis.lang.interpreter.impl.AbstractAnnotatedTree.forEachWithIndex(AbstractAnnotatedTree.java:188)
    at org.protelis.lang.interpreter.impl.AbstractAnnotatedTree.projectAndEval(AbstractAnnotatedTree.java:228)
    at org.protelis.lang.interpreter.impl.CreateVar.eval(CreateVar.java:45)
    at org.protelis.lang.interpreter.impl.All.lambda$eval$0(All.java:48)
    at org.protelis.lang.interpreter.impl.All.access$lambda$0(All.java)
    at org.protelis.lang.interpreter.impl.All$$Lambda$1.accept(Unknown Source)
    at org.protelis.lang.interpreter.impl.AbstractAnnotatedTree.forEachWithIndex(AbstractAnnotatedTree.java:188)
    at org.protelis.lang.interpreter.impl.All.eval(All.java:46)
    at org.protelis.vm.impl.SimpleProgramImpl.compute(SimpleProgramImpl.java:81)
    at org.protelis.vm.ProtelisVM.runCycle(ProtelisVM.java:45)
    at com.bbn.ccast.Main.update(Main.java:372)
    at com.bbn.ccast.Main.main(Main.java:150)
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.GeneratedMethodAccessor33.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.protelis.lang.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:229)
    ... 27 more
Caused by: java.util.ConcurrentModificationException
    at java.util.HashMap$HashIterator.nextNode(HashMap.java:1442)
    at java.util.HashMap$KeyIterator.next(HashMap.java:1466)
    at com.bbn.ccast.vehicle.ProtelisDevice.mergeAprilTags(ProtelisDevice.java:1049)
    ... 31 more
```

**Comment by DanySK** [comment] 2019-03-27 09:41
Thank you. By looking at the stacktrace, I see that the original error's stacktrace does not get erased (that would be rather painful). For the first point you raise, I believe that 5d5f9e06f30fce1487fbe51d5f557358637cba61 contains a reasonable fix already, with the latest beta the error message should look like:
```
java.lang.IllegalStateException: Cannot invoke public static java.util.Set com.bbn.SOME_METHOD(java.util.Set,java.util.Set) with arguments [REASONABLE_ARGUMENTS]
```

For the second point, one strategy could be to differentiate among `IllegalAccessException`, `IllegalArgumentException`, and `InvocationTargetException`, the case you describe fall in the latter, and we might add a note in the main message on the cause of the `InvocationTargetException`. Something like:
```
java.lang.IllegalStateException: Execution of public static java.util.Set com.bbn.SOME_METHOD(java.util.Set,java.util.Set) with arguments [REASONABLE_ARGUMENTS] failed due to a java.util.ConcurrentModificationException. Please look at the stacktrace for further information
```

**Comment by jakebeal** [comment] 2019-03-27 11:00
Yes, this sounds like a reasonable strategy.

**Comment by DanySK** [comment] 2019-03-27 16:23
I believe ee1f814 is a fix for this. Please close if you agree.

**Comment by jakebeal** [comment] 2019-03-27 18:34
I agree; please close via resolution of a pull request.

**Comment by DanySK** [comment] 2019-03-29 13:35
The fix is in develop already. I'll make sure to pass through pull requests from now on to improve issue tracking.

**Closed by DanySK** 2019-03-29 13:35 UTC
Labels: bug
