### ISSUE TITLE
distanceCompetition doesn't use metric

### ISSUE THREAD

**Issue by jakebeal** [Protelis/Protelis#150] opened 2018-02-16 20:07 UTC
The distanceCompetition function has a metric argument:

`def distanceCompetition(d, lead, uid, grain, metric)`

but it doesn't use it.  Either it's redundant and should be removed or there is a bug.

**Comment by DanySK** [comment] 2019-03-26 13:39
Duplicate of #163 (actually #163 is a duplicate of this one). Anyway, problem solved.

**Closed by DanySK** 2019-03-26 13:39 UTC
Labels: bug, duplicate
