### ISSUE TITLE
Can't use Swing with Eclipse projects directly linked to Protelis and Protelis-Parser 

### ISSUE THREAD

**Issue by jakebeal** [Protelis/Protelis#12] opened 2015-07-22 19:04 UTC
If an Eclipse project is linked directly both to Protelis and through it to Protelis-Parser (rather than via Gradle/Maven), then when Eclipse is run Swing UIs will fail to appear.  The program still runs correctly if invoked from the command line, and also runs correctly if Protelis-Parser is linked via a jar Gradle rather than as a cross-project dependency in the workspace.

A simple Swing hello-world is enough to diagnose the presence of the problem:

```
import javax.swing.JFrame;
import javax.swing.JLabel;

public class MinimalFailure {
    public static void main(String[] args) throws Exception {
        JFrame frame = new JFrame("HelloWorldSwing");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setSize(300,200);

        //Add the ubiquitous "Hello World" label.
        JLabel label = new JLabel("Hello World");
        frame.getContentPane().add(label);

        frame.setVisible(true);
    }
}
```

**Comment by DanySK** [comment] 2015-07-23 09:33
This is more than weird, and I doubt it can be protelis-related in any way. Protelis has no interaction with swing whatsoever. Could you please extract from eclipse the command that is producing a failure?
(https://wiki.eclipse.org/FAQ_How_do_I_find_out_the_command-line_arguments_of_a_launched_program%3F)

Does the same failure happen if you launch this exact command on a terminal?

**Comment by jakebeal** [comment] 2015-07-23 13:58
Here is the Eclipse command: 

/Library/Java/JavaVirtualMachines/jdk1.8.0_20.jdk/Contents/Home/bin/java -XstartOnFirstThread -Dfile.encoding=UTF-8 -classpath /Users/jakebeal/projects/Protelis/protelis_workspace/minimal-failure/bin:/Users/jakebeal/projects/Protelis/protelis_workspace/Protelis/bin:/Users/jakebeal/.gradle/caches/modules-2/files-2.1/aopalliance/aopalliance/1.0/235ba8b489512805ac13a8f9ea77a1ca5ebe3e8/aopalliance-1.0.jar:/Users/jakebeal/.gradle/caches/modules-2/files-2.1/asm/asm/3.1/c157def142714c544bdea2e6144645702adf7097/asm-3.1.jar:/Users/jakebeal/.gradle/caches/modules-2/files-2.1/com.apple/AppleJavaExtensions/1.4/c586cd0b44cae8c0239a977277f99d08d751a482/AppleJavaExtensions-1.4.jar:/Users/jakebeal/.gradle/caches/modules-2/files-2.1/com.google.code.findbugs/annotations/2.0.1/9ef6656259841cebfb9fb0697bb122ada4485498/annotations-2.0.1.jar:/Users/jakebeal/.gradle/caches/modules-2/files-2.1/com.google.code.findbugs/bcel-findbugs/6.0/7a7563ba41dceff3da4af4927b7c09908bd5132c/bcel-findbugs-6.0.jar:/Users/jakebeal/.gradle/caches/modules-2/files-2.1/com.google.code.findbugs/findbugs/3.0.1/7ae69957c437fd71628d3904572170cf80c01551/findbugs-3.0.1.jar:/Users/jakebeal/.gradle/caches/modules-2/files-2.1/com.google.code.findbugs/jFormatString/2.0.1/686faafff86cdde6e75975149a1be8f9b6dbb7c0/jFormatString-2.0.1.jar:/Users/jakebeal/.gradle/caches/modules-2/files-2.1/com.google.code.findbugs/jsr305/2.0.1/516c03b21d50a644d538de0f0369c620989cd8f0/jsr305-2.0.1.jar:/Users/jakebeal/.gradle/caches/modules-2/files-2.1/com.google.code.gson/gson/2.3.1/ecb6e1f8e4b0e84c4b886c2f14a1500caf309757/gson-2.3.1.jar:/Users/jakebeal/.gradle/caches/modules-2/files-2.1/com.google.guava/guava/18.0/cce0823396aa693798f8882e64213b1772032b09/guava-18.0.jar:/Users/jakebeal/.gradle/caches/modules-2/files-2.1/com.google.inject/guice/3.0/9d84f15fe35e2c716a02979fb62f50a29f38aefa/guice-3.0.jar:/Users/jakebeal/.gradle/caches/modules-2/files-2.1/com.google.protobuf/protobuf-java/2.6.1/d9521f2aecb909835746b7a5facf612af5e890e8/protobuf-java-2.6.1.jar:/Users/jakebeal/.gradle/caches/modules-2/files-2.1/com.graphhopper/graphhopper/0.4.1/1bf6ba449a248065d42f337b231e01205189f59a/graphhopper-0.4.1.jar:/Users/jakebeal/.gradle/caches/modules-2/files-2.1/com.ibm.icu/icu4j/52.1/7dbc327670673acd14b487d120f05747d712c1c0/icu4j-52.1.jar:/Users/jakebeal/.gradle/caches/modules-2/files-2.1/com.javadocmd/simplelatlng/1.3.0/b081d20d8ed560dd8964fca0b6a0a68a97fe5535/simplelatlng-1.3.0.jar:/Users/jakebeal/.gradle/caches/modules-2/files-2.1/commons-io/commons-io/2.4/b1b6ea3b7e4aa4f492509a4952029cd8e48019ad/commons-io-2.4.jar:/Users/jakebeal/.gradle/caches/modules-2/files-2.1/commons-lang/commons-lang/2.6/ce1edb914c94ebc388f086c6827e8bdeec71ac2/commons-lang-2.6.jar:/Users/jakebeal/.gradle/caches/modules-2/files-2.1/commons-logging/commons-logging/1.2/4bfc12adfe4842bf07b657f0369c4cb522955686/commons-logging-1.2.jar:/Users/jakebeal/.gradle/caches/modules-2/files-2.1/dom4j/dom4j/1.6.1/5d3ccc056b6f056dbf0dddfdf43894b9065a8f94/dom4j-1.6.1.jar:/Users/jakebeal/.gradle/caches/modules-2/files-2.1/it.unibo.alchemist/alchemist-baselib/1.0.0/8208e80ed0352c28f2e60f7b97762ff6d0dfd4e/alchemist-baselib-1.0.0.jar:/Users/jakebeal/.gradle/caches/modules-2/files-2.1/it.unibo.alchemist/alchemist-engine/0.1.0/87b835ae0389d282648d067aa25ebebde6772efb/alchemist-engine-0.1.0.jar:/Users/jakebeal/.gradle/caches/modules-2/files-2.1/it.unibo.alchemist/alchemist-enginedependentmodel/0.2.0/bd119b6d6e65d3abfe83d81c256fbaba646e602b/alchemist-enginedependentmodel-0.2.0.jar:/Users/jakebeal/.gradle/caches/modules-2/files-2.1/it.unibo.alchemist/alchemist-implementationbase/4.0.0/dc18508f648238de731d72d2fa0fc85e245afac2/alchemist-implementationbase-4.0.0.jar:/Users/jakebeal/.gradle/caches/modules-2/files-2.1/it.unibo.alchemist/alchemist-interfaces/2.0.1/9211f53ed2b2e653908cf86dd24dbb5f5d09e2fd/alchemist-interfaces-2.0.1.jar:/Users/jakebeal/.gradle/caches/modules-2/files-2.1/it.unibo.alchemist/alchemist-maps/2.1.0/10594795081ec07c95825e7cc47a04c579baac96/alchemist-maps-2.1.0.jar:/Users/jakebeal/.gradle/caches/modules-2/files-2.1/it.unibo.alchemist/alchemist-time/0.1.0/4ae10af42bcb3b4b4c4421aed97e7be7be00fee0/alchemist-time-0.1.0.jar:/Users/jakebeal/.gradle/caches/modules-2/files-2.1/it.unibo.alchemist/alchemist.protelisdsl/3.0.2/3be156c6a101dec579d97f54bafa0a82cc87aeb1/alchemist.protelisdsl-3.0.2.jar:/Users/jakebeal/.gradle/caches/modules-2/files-2.1/it.unibo.alice.tuprolog/tuprolog/2.1.1/88c922df1007377b2723e2fdb78ea4030d30af78/tuprolog-2.1.1.jar:/Users/jakebeal/.gradle/caches/modules-2/files-2.1/javax.inject/javax.inject/1/6975da39a7040257bd51d21a231b76c915872d38/javax.inject-1.jar:/Users/jakebeal/.gradle/caches/modules-2/files-2.1/jaxen/jaxen/1.1.6/3f8c36d9a0578e8e98f030c662b69888b1430ac0/jaxen-1.1.6.jar:/Users/jakebeal/.gradle/caches/modules-2/files-2.1/junit/junit/4.12/2973d150c0dc1fefe998f834810d68f278ea58ec/junit-4.12.jar:/Users/jakebeal/.gradle/caches/modules-2/files-2.1/log4j/log4j/1.2.16/7999a63bfccbc7c247a9aea10d83d4272bd492c6/log4j-1.2.16.jar:/Users/jakebeal/.gradle/caches/modules-2/files-2.1/net.jcip/jcip-annotations/1.0/afba4942caaeaf46aab0b976afd57cc7c181467e/jcip-annotations-1.0.jar:/Users/jakebeal/.gradle/caches/modules-2/files-2.1/net.sf.trove4j/trove4j/3.0.3/42ccaf4761f0dfdfa805c9e340d99a755907e2dd/trove4j-3.0.3.jar:/Users/jakebeal/.gradle/caches/modules-2/files-2.1/org.antlr/antlr-runtime/3.2/31c746001016c6226bd7356c9f87a6a084ce3715/antlr-runtime-3.2.jar:/Users/jakebeal/.gradle/caches/modules-2/files-2.1/org.apache.commons/commons-lang3/3.4/5fe28b9518e58819180a43a850fbc0dd24b7c050/commons-lang3-3.4.jar:/Users/jakebeal/.gradle/caches/modules-2/files-2.1/org.apache.commons/commons-math3/3.5/13af68e9a11576953f5c4b09436f8207be9d3a27/commons-math3-3.5.jar:/Users/jakebeal/.gradle/caches/modules-2/files-2.1/org.apache.xmlgraphics/xmlgraphics-commons/1.5/7fb5c2b2c18f0e87fbe9bded16429a5d7cc2dc2b/xmlgraphics-commons-1.5.jar:/Users/jakebeal/.gradle/caches/modules-2/files-2.1/org.danilopianini/javalib-java7/0.0.2/c42ef4317d8de9c3f660b78fd028da3ae417dd2b/javalib-java7-0.0.2.jar:/Users/jakebeal/.gradle/caches/modules-2/files-2.1/org.danilopianini/javalib/3.0.0/ac44ad94b8638c6d1088d8ab6a9e8c46946cac7d/javalib-3.0.0.jar:/Users/jakebeal/.gradle/caches/modules-2/files-2.1/org.eclipse.core/contenttype/3.4.200-v20140207-1251/db44eacfdced003f806846810b1a62a1066bb8fd/contenttype-3.4.200-v20140207-1251.jar:/Users/jakebeal/.gradle/caches/modules-2/files-2.1/org.eclipse.core/jobs/3.6.0-v20140424-0053/4f355c5efd8a39a03f7b0ff4cfcf24b33a968c12/jobs-3.6.0-v20140424-0053.jar:/Users/jakebeal/.gradle/caches/modules-2/files-2.1/org.eclipse.core/runtime/3.10.0-v20140318-2214/a537de26c1e322a68536a3a2c3cb2389d5dbcb00/runtime-3.10.0-v20140318-2214.jar:/Users/jakebeal/.gradle/caches/modules-2/files-2.1/org.eclipse.emf/org.eclipse.emf.codegen/2.10.0/ab49c04e96b44a58d2e13cbc1ffb42c4cc9b613a/org.eclipse.emf.codegen-2.10.0.jar:/Users/jakebeal/.gradle/caches/modules-2/files-2.1/org.eclipse.emf/org.eclipse.emf.common/2.11.0-v20150123-0347/74b15754d8d84521916be0e6aecca485f5e555ff/org.eclipse.emf.common-2.11.0-v20150123-0347.jar:/Users/jakebeal/.gradle/caches/modules-2/files-2.1/org.eclipse.emf/org.eclipse.emf.ecore.xmi/2.11.0-v20150123-0347/c67fece586c58f4bfe15d8e6c354621c9b2dc7ec/org.eclipse.emf.ecore.xmi-2.11.0-v20150123-0347.jar:/Users/jakebeal/.gradle/caches/modules-2/files-2.1/org.eclipse.emf/org.eclipse.emf.ecore/2.11.0-v20150123-0347/69b47ef7d4a67654b34f7216c3dbaaf1890fad5d/org.eclipse.emf.ecore-2.11.0-v20150123-0347.jar:/Users/jakebeal/.gradle/caches/modules-2/files-2.1/org.eclipse.emf/org.eclipse.emf.mwe.core/1.3.5/18fe747e59ae57a93cbadec165de88bea90eb222/org.eclipse.emf.mwe.core-1.3.5.jar:/Users/jakebeal/.gradle/caches/modules-2/files-2.1/org.eclipse.emf/org.eclipse.emf.mwe.utils/1.3.5/c200466ad77312a426769b73d3f7a62537aa8657/org.eclipse.emf.mwe.utils-1.3.5.jar:/Users/jakebeal/.gradle/caches/modules-2/files-2.1/org.eclipse.equinox/app/1.3.200-v20130910-1609/659921d8f404ee6161c29bd6a6798631208c3633/app-1.3.200-v20130910-1609.jar:/Users/jakebeal/.gradle/caches/modules-2/files-2.1/org.eclipse.equinox/common/3.6.200-v20130402-1505/5354112138f6e420a8152fc9526b15f25ed5f163/common-3.6.200-v20130402-1505.jar:/Users/jakebeal/.gradle/caches/modules-2/files-2.1/org.eclipse.equinox/preferences/3.5.200-v20140224-1527/9ea0f3c0b18d0a1e904743b19c2f7c0c7163c61e/preferences-3.5.200-v20140224-1527.jar:/Users/jakebeal/.gradle/caches/modules-2/files-2.1/org.eclipse.equinox/registry/3.5.400-v20140428-1507/5f933a7fbea4c96c74c50b4d453e59b3185e6aec/registry-3.5.400-v20140428-1507.jar:/Users/jakebeal/.gradle/caches/modules-2/files-2.1/org.eclipse.xtext/org.eclipse.xtext.common.types/2.8.3/ea08352eb5ec2148f9051484eae6c5ed4a2a685d/org.eclipse.xtext.common.types-2.8.3.jar:/Users/jakebeal/.gradle/caches/modules-2/files-2.1/org.eclipse.xtext/org.eclipse.xtext.util/2.8.3/a724c4580827837cf627daad105f56dd6ef55070/org.eclipse.xtext.util-2.8.3.jar:/Users/jakebeal/.gradle/caches/modules-2/files-2.1/org.eclipse.xtext/org.eclipse.xtext.xbase.lib/2.8.3/f4f5a87bf2536f975e8565a05cb79259c80e5f93/org.eclipse.xtext.xbase.lib-2.8.3.jar:/Users/jakebeal/.gradle/caches/modules-2/files-2.1/org.eclipse.xtext/org.eclipse.xtext/2.8.3/26954af1d8a0468d297de2315b25ab8f20437228/org.eclipse.xtext-2.8.3.jar:/Users/jakebeal/.gradle/caches/modules-2/files-2.1/org.eclipse/osgi/3.10.0-v20140606-1445/afe258a6e5d2dcd8fa4c894f53fdc78e49984e3c/osgi-3.10.0-v20140606-1445.jar:/Users/jakebeal/.gradle/caches/modules-2/files-2.1/org.hamcrest/hamcrest-core/1.3/42a25dc3219429f0e5d060061f71acb49bf010a0/hamcrest-core-1.3.jar:/Users/jakebeal/.gradle/caches/modules-2/files-2.1/org.javassist/javassist/3.18.2-GA/1180a90fbad732b60fb728a6bbe8fcb3151423d7/javassist-3.18.2-GA.jar:/Users/jakebeal/.gradle/caches/modules-2/files-2.1/org.openstreetmap.osmosis/osmosis-osm-binary/0.43.1/1c92d0d8fef6d0f40d2793238b821eb74aa543f1/osmosis-osm-binary-0.43.1.jar:/Users/jakebeal/.gradle/caches/modules-2/files-2.1/org.ow2.asm/asm-commons/5.0.2/33fd77f7d9f985e4b9bee5e4c3a4e480c491c404/asm-commons-5.0.2.jar:/Users/jakebeal/.gradle/caches/modules-2/files-2.1/org.ow2.asm/asm-debug-all/5.0.2/5742eaa4eb2f0583b642eb2a2a7597c996139103/asm-debug-all-5.0.2.jar:/Users/jakebeal/.gradle/caches/modules-2/files-2.1/org.ow2.asm/asm-tree/5.0.2/407b3da4cdb780701be40ccf6e8ef540f3d5a249/asm-tree-5.0.2.jar:/Users/jakebeal/.gradle/caches/modules-2/files-2.1/org.ow2.asm/asm/5.0.2/baa28ca0269720d94c9f0cafef35a9ac63991de7/asm-5.0.2.jar:/Users/jakebeal/.gradle/caches/modules-2/files-2.1/org.reflections/reflections/0.9.10/c7f4ea230aedc757ca1499ebcfb2953c81cf8b67/reflections-0.9.10.jar:/Users/jakebeal/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-api/1.7.10/5b338f206827d88acd890739f400a9b7664e5984/slf4j-api-1.7.10.jar:/Users/jakebeal/.gradle/caches/modules-2/files-2.1/org.sonatype.sisu.inject/cglib/2.2.1-v20090111/7ce5e983fd0e6c78346f4c9cbfa39d83049dda2/cglib-2.2.1-v20090111.jar:/Users/jakebeal/.gradle/caches/modules-2/files-2.1/org.springframework/spring-core/4.1.6.RELEASE/e2f486124d5dea2d91a9c2ea7d4456bc343ca2cc/spring-core-4.1.6.RELEASE.jar:/Users/jakebeal/.gradle/caches/modules-2/files-2.1/xml-apis/xml-apis/1.0.b2/3136ca936f64c9d68529f048c2618bd356bf85c9/xml-apis-1.0.b2.jar:/Users/jakebeal/Desktop/eclipse/plugins/org.eclipse.xtext_2.7.3.v201411190455.jar:/Users/jakebeal/Desktop/eclipse/plugins/org.eclipse.emf.ecore.xmi_2.10.2.v20150123-0348.jar:/Users/jakebeal/Desktop/eclipse/plugins/org.eclipse.emf.ecore_2.10.2.v20150123-0348.jar:/Users/jakebeal/Desktop/eclipse/plugins/org.eclipse.emf.common_2.10.1.v20150123-0348.jar:/Users/jakebeal/Desktop/eclipse/plugins/org.antlr.runtime_3.2.0.v201101311130.jar:/Users/jakebeal/Desktop/eclipse/plugins/com.google.inject_3.0.0.v201312141243.jar:/Users/jakebeal/Desktop/eclipse/plugins/org.eclipse.emf.mwe.core_1.3.5.v201503051048.jar:/Users/jakebeal/Desktop/eclipse/plugins/org.apache.commons.cli_1.2.0.v201404270220.jar:/Users/jakebeal/Desktop/eclipse/plugins/org.eclipse.emf.mwe2.runtime_2.7.1.v201503051048.jar:/Users/jakebeal/Desktop/eclipse/plugins/org.eclipse.emf.mwe.utils_1.3.5.v201503051048.jar:/Users/jakebeal/Desktop/eclipse/plugins/org.eclipse.xtext.util_2.7.3.v201411190455.jar:/Users/jakebeal/Desktop/eclipse/plugins/com.google.guava_15.0.0.v201403281430.jar:/Users/jakebeal/Desktop/eclipse/plugins/javax.inject_1.0.0.v20091030.jar:/Users/jakebeal/Desktop/eclipse/plugins/org.eclipse.xtext.xbase_2.7.3.v201411190455.jar:/Users/jakebeal/Desktop/eclipse/plugins/org.eclipse.xtext.common.types_2.7.3.v201411190455.jar:/Users/jakebeal/Desktop/eclipse/plugins/org.eclipse.xtend.lib_2.7.3.v201411190455.jar:/Users/jakebeal/Desktop/eclipse/plugins/org.eclipse.xtext.xbase.lib_2.7.3.v201411190455.jar:/Users/jakebeal/Desktop/eclipse/plugins/org.eclipse.xtend.lib.macro_2.7.3.v201411190455.jar:/Users/jakebeal/Desktop/eclipse/plugins/org.eclipse.xtext.generator_2.7.3.v201411190455.jar:/Users/jakebeal/Desktop/eclipse/plugins/org.eclipse.xtend_2.0.0.v201406030414.jar:/Users/jakebeal/Desktop/eclipse/plugins/com.ibm.icu_52.1.0.v201404241930.jar:/Users/jakebeal/Desktop/eclipse/plugins/org.eclipse.xpand_2.0.0.v201406030414.jar:/Users/jakebeal/Desktop/eclipse/plugins/org.eclipse.xtend.typesystem.emf_2.0.0.v201406030414.jar:/Users/jakebeal/Desktop/eclipse/plugins/org.eclipse.emf.codegen.ecore_2.10.2.v20150123-0452.jar:/Users/jakebeal/Desktop/eclipse/plugins/org.eclipse.emf.codegen_2.10.0.v20150123-0452.jar:/Users/jakebeal/Desktop/eclipse/plugins/de.itemis.xtext.antlr_2.1.1.v201405091103.jar:/Users/jakebeal/Desktop/eclipse/plugins/org.antlr.generator_3.2.0.v201405091103.jar:/Users/jakebeal/Desktop/eclipse/plugins/org.eclipse.emf.mwe2.lib_2.7.1.v201503051048.jar:/Users/jakebeal/Desktop/eclipse/plugins/org.apache.commons.logging_1.1.1.v201101211721.jar:/Users/jakebeal/Desktop/eclipse/plugins/org.eclipse.emf.mwe2.launch_2.7.1.v201503051215.jar:/Users/jakebeal/Desktop/eclipse/plugins/org.eclipse.emf.mwe2.language_2.7.1.v201503051215.jar:/Users/jakebeal/Desktop/eclipse/plugins/org.eclipse.equinox.common_3.6.200.v20130402-1505.jar:/Users/jakebeal/Desktop/eclipse/plugins/org.objectweb.asm_5.0.1.v201404251740.jar:/Users/jakebeal/Desktop/eclipse/plugins/org.apache.log4j_1.2.15.v201012070815.jar:/Users/jakebeal/projects/Protelis/protelis_workspace/Protelis-Parser/alchemist.protelis/target/classes:/Users/jakebeal/Desktop/eclipse/plugins/org.eclipse.xtext.ui_2.7.3.v201411190455.jar:/Users/jakebeal/Desktop/eclipse/plugins/org.eclipse.core.runtime_3.10.0.v20140318-2214.jar:/Users/jakebeal/Desktop/eclipse/plugins/javax.annotation_1.2.0.v201401042248.jar:/Users/jakebeal/Desktop/eclipse/plugins/org.eclipse.osgi_3.10.0.v20140606-1445.jar:/Users/jakebeal/Desktop/eclipse/plugins/org.eclipse.fx.osgi_1.2.0.201501301028.jar:/Users/jakebeal/Desktop/eclipse/plugins/org.eclipse.osgi.compatibility.state_1.0.0.v20140403-1907.jar:/Users/jakebeal/Desktop/eclipse/plugins/org.eclipse.core.jobs_3.6.0.v20140424-0053.jar:/Users/jakebeal/Desktop/eclipse/plugins/org.eclipse.core.runtime.compatibility.registry_3.5.300.v20140128-0851/runtime_registry_compatibility.jar:/Users/jakebeal/Desktop/eclipse/plugins/org.eclipse.equinox.registry_3.5.400.v20140428-1507.jar:/Users/jakebeal/Desktop/eclipse/plugins/org.eclipse.equinox.preferences_3.5.200.v20140224-1527.jar:/Users/jakebeal/Desktop/eclipse/plugins/org.eclipse.core.contenttype_3.4.200.v20140207-1251.jar:/Users/jakebeal/Desktop/eclipse/plugins/org.eclipse.equinox.app_1.3.200.v20130910-1609.jar:/Users/jakebeal/Desktop/eclipse/plugins/org.eclipse.core.resources_3.9.0.v20140514-1307.jar:/Users/jakebeal/Desktop/eclipse/plugins/org.eclipse.ui_3.106.0.v20140519-0906.jar:/Users/jakebeal/Desktop/eclipse/plugins/org.eclipse.swt_3.103.0.v20140605-2008.jar:/Users/jakebeal/Desktop/eclipse/plugins/org.eclipse.swt.cocoa.macosx.x86_64_3.103.0.v20140605-2012.jar:/Users/jakebeal/Desktop/eclipse/plugins/org.eclipse.jface_3.10.0.v20140604-0740.jar:/Users/jakebeal/Desktop/eclipse/plugins/org.eclipse.core.commands_3.6.100.v20140528-1422.jar:/Users/jakebeal/Desktop/eclipse/plugins/org.eclipse.ui.workbench_3.106.0.v20140530-0732.jar:/Users/jakebeal/Desktop/eclipse/plugins/org.eclipse.e4.ui.workbench3_0.12.0.v20140227-2118.jar:/Users/jakebeal/Desktop/eclipse/plugins/org.eclipse.ui.editors_3.8.200.v20140401-1310.jar:/Users/jakebeal/Desktop/eclipse/plugins/org.eclipse.core.filebuffers_3.5.400.v20140127-1516.jar:/Users/jakebeal/Desktop/eclipse/plugins/org.eclipse.jface.text_3.9.0.v20140521-1657.jar:/Users/jakebeal/Desktop/eclipse/plugins/org.eclipse.text_3.5.300.v20130515-1451.jar:/Users/jakebeal/Desktop/eclipse/plugins/org.eclipse.emf.edit.ui_2.10.2.v20150123-0452.jar:/Users/jakebeal/Desktop/eclipse/plugins/org.eclipse.ui.views_3.7.0.v20140408-0703.jar:/Users/jakebeal/Desktop/eclipse/plugins/org.eclipse.emf.edit_2.10.1.v20150123-0452.jar:/Users/jakebeal/Desktop/eclipse/plugins/org.eclipse.emf.ecore.change_2.10.0.v20150123-0348.jar:/Users/jakebeal/Desktop/eclipse/plugins/org.eclipse.emf.common.ui_2.9.0.v20150123-0452.jar:/Users/jakebeal/Desktop/eclipse/plugins/org.eclipse.ltk.core.refactoring_3.6.100.v20140520-1248.jar:/Users/jakebeal/Desktop/eclipse/plugins/org.eclipse.ui.ide_3.10.0.v20140521-1937.jar:/Users/jakebeal/Desktop/eclipse/plugins/org.eclipse.xtext.ui.shared_2.7.3.v201411190455.jar:/Users/jakebeal/Desktop/eclipse/plugins/org.eclipse.xtext.builder_2.7.3.v201411190455.jar:/Users/jakebeal/Desktop/eclipse/plugins/org.eclipse.debug.ui_3.10.0.v20140604-1637.jar:/Users/jakebeal/Desktop/eclipse/plugins/org.eclipse.debug.core_3.9.0.v20140521-1435.jar:/Users/jakebeal/Desktop/eclipse/plugins/org.eclipse.xtext.common.types.ui_2.7.3.v201411190455.jar:/Users/jakebeal/Desktop/eclipse/plugins/org.eclipse.xtext.common.types.edit_2.7.3.v201411190455.jar:/Users/jakebeal/Desktop/eclipse/plugins/org.eclipse.xtext.ui.codetemplates.ui_2.7.3.v201411190455.jar:/Users/jakebeal/Desktop/eclipse/plugins/org.eclipse.xtext.ui.codetemplates_2.7.3.v201411190455.jar:/Users/jakebeal/Desktop/eclipse/plugins/org.eclipse.compare_3.5.500.v20131106-1552.jar:/Users/jakebeal/Desktop/eclipse/plugins/org.eclipse.compare.core_3.5.400.v20130903-0736.jar:/Users/jakebeal/Desktop/eclipse/plugins/org.eclipse.ui.workbench.texteditor_3.9.0.v20140411-1521.jar:/Users/jakebeal/projects/Protelis/protelis_workspace/Protelis-Parser/alchemist.protelis.ui/target/classes MinimalFailure

**Comment by jakebeal** [comment] 2015-07-23 13:59
Running this command from the command line also produces the identical failure.

Internet sources suggest that the problem is some sort of conflict in the dependencies of Protelis-Parser and something else.

**Comment by jakebeal** [comment] 2015-07-23 14:04
Aha: more investigation reveals a clearer locus of the bug.

The bug is caused by including the alchemist.protelis.ui project

* Include alchemist.protelis: no bug
* Include alchemist.protelis.ui: bug
* Include both: bug
* Include Protelis (which includes ui via Gradle): bug
* Include Protelis with alchemist.protelis.ui closed (so the jar is used instead): no bug

**Comment by jakebeal** [comment] 2015-07-23 14:12
So I think that including the Eclipse plugin is the problem (which maybe is less surprising).
The real question is: why is the Eclipse plugin getting included?
The gradle line is:

        compile "it.unibo.alchemist:alchemist.protelis:$protelisVersion"

Why does that cause alchemist.protelis.ui to be included as well?
I can't figure it out, but you've got a lot more gradle experience than I...

**Comment by jakebeal** [comment] 2015-07-23 14:27
Aha!  In the alchemist.protelis project in Protelis-Parser, the pom.xml has the following:

			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-clean-plugin</artifactId>
				<configuration>
					<filesets combine.children="append">
						<fileset>
							<directory>${basedir}/src-gen/</directory>
						</fileset>
						<fileset>
							<directory>${basedir}/model/generated/</directory>
						</fileset>
						<fileset>
							<directory>${basedir}/../${project.artifactId}.ui/src-gen/</directory>
						</fileset>
						<fileset>
							<directory>${basedir}/../${project.artifactId}.tests/src-gen/</directory>
						</fileset>
					</filesets>
				</configuration>
			</plugin>

It's including .ui

**Comment by DanySK** [comment] 2015-07-23 14:28
This is just a "delete the content of ${basedir}/../${project.artifactId}.ui/src-gen/", should not imply any dependency.

**Comment by jakebeal** [comment] 2015-08-07 20:35
I've added this to release 4.1 because we need to either fix it or document as a known issue before the first major release.

**Comment by DanySK** [comment] 2019-03-29 16:20
I'm closing this as Protelis does not depend on Alchemist anymore (besides for testing). The Xtext DSL that was the root cause of the problem has been dropped years ago. If it is still an issue somehow, I would suggest not reopening this one but rather a new one (there is very little information we can use for bug hunting from four years ago...)

**Closed by DanySK** 2019-03-29 16:20 UTC
Labels: bug
