### ISSUE TITLE
Compilation errors don't point back to line numbers

### ISSUE THREAD

**Issue by jakebeal** [Protelis/Protelis#168] opened 2019-03-29 00:36 UTC
As reported by @jschewebbn:
> things that usually give me issues:
> - compilation errors that don't point back to a line number in my file.

**Comment by DanySK** [comment] 2019-03-29 13:13
Duplicate of #145. Please reopen if I'm wrong.

**Comment by jakebeal** [comment] 2019-03-29 13:40
#145 is about execution errors. This is about compilation errors.

**Comment by DanySK** [comment] 2019-03-29 15:37
Thanks.
However, it is not entirely clear to me: Protelis is interpreted, it does not go through a true compilation stage . Does the issue refer to the conversion between the Xtext entities and the Protelis internal entities? Or does this refer to the Eclipse plugin?

**Comment by jakebeal** [comment] 2019-03-29 15:45
@jschewebbn: can you elaborate for Danilo on the problem you've encountered?

**Comment by jschewebbn** [comment] 2019-03-29 15:56
Given that Protelis is interpreted, perhaps it's the same as #145. If there is a syntax error, I remember it being rather difficult to track down which Protelis file had the actual error and which line had the error. It's been many months since I was writing Protelis code, so I don't have any specific examples. At the time I ended up doing a binary search across each code file until I found the line that caused the error. Then I usually need to ask Jake why it was a problem.

**Comment by jakebeal** [comment] 2019-04-02 18:42
In general, we need a recommended "fail-fast" path, particularly given that the Eclipse plug-in doesn't predict failure well.

**Comment by jakebeal** [comment] 2019-04-02 21:25
@jschewebbn adds: 
>One that is either part of 168 or related is that when I mark a folder as derived the Eclipse plugin keeps checking the files in that directory. I suspect this is the source of most of my errors.

**Comment by jakebeal** [comment] 2019-04-17 10:25
@jschewebbn Can you please look for an example of this problem? Until we find one, this might be assumed to be solved by #145

**Comment by jschewebbn** [comment] 2019-04-17 13:06
I suggest we close this ticket until I find a specific case with the new version of Protelis.

**Comment by DanySK** [comment] 2019-04-17 13:25
Closing then

**Closed by DanySK** 2019-04-17 13:25 UTC
Labels: Priority 2, enhancement, question
